# Generated by Django 4.2.23 on 2025-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(),
        ),
    ]
