# Generated by Django 4.2.23 on 2025-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_remove_project_technologies_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.ManyToManyField(blank=True, related_name='categories', to='mywebsite.skill')),
            ],
        ),
    ]
