# Generated by Django 4.2.23 on 2025-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_skillcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
